name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 unittests:
   uses: esantix/workflows/.github/workflows/python_unittest.yml@v1
   with:
     requirements: -r requirements.dev.txt .
