name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@main
   - name: Run unit tests
     run: |
      pip install -r requirements.dev.txt
      coverage run -m unittest discover -s ./tests -p 'test_*.py'
      coverage report -m
