name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@main
   - name: install
     run: make install  
   - name: build application
     run: make test